"""Cambios varios

Revision ID: 00df55b1a32b
Revises: e91b8c6ce9cf
Create Date: 2025-03-02 11:42:25.723361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00df55b1a32b'
down_revision: Union[str, None] = 'e91b8c6ce9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_deck_id_key', 'games', type_='unique')
    op.drop_column('games', 'deck_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('games_deck_id_key', 'games', ['deck_id'])
    # ### end Alembic commands ###
