"""Prueba2

Revision ID: 194b803add96
Revises: 00b8e3b6e4b7
Create Date: 2025-02-26 19:10:25.955266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '194b803add96'
down_revision: Union[str, None] = '00b8e3b6e4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_bodies_id', table_name='player_bodies')
    op.drop_table('player_bodies')
    op.drop_constraint('players_game_id_fkey', 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_column('players', 'body_cards')
    op.drop_column('players', 'hand_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('hand_cards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('body_cards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key('players_game_id_fkey', 'players', 'games', ['game_id'], ['id'])
    op.create_table('player_bodies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='player_bodies_player_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='player_bodies_pkey')
    )
    op.create_index('ix_player_bodies_id', 'player_bodies', ['id'], unique=False)
    # ### end Alembic commands ###
