"""Modelchanged

Revision ID: 1dc2fbeb1286
Revises: 9a4e4d6badc5
Create Date: 2025-05-01 18:58:34.138990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc2fbeb1286'
down_revision: Union[str, None] = '9a4e4d6badc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moves', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moves', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
