"""Changing organ restrictions 

Revision ID: 27e15fcf7b62
Revises: d0baecb2527d
Create Date: 2025-04-23 20:28:13.200422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e15fcf7b62'
down_revision: Union[str, None] = 'd0baecb2527d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
