"""Move modified 2

Revision ID: 3c5cfa510c3c
Revises: e8e811ed3179
Create Date: 2025-05-14 20:39:26.538669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5cfa510c3c'
down_revision: Union[str, None] = 'e8e811ed3179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('lungs_estado', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('intestine_estado', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('heart_estado', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('brain_estado', sa.Integer(), nullable=True))
    op.add_column('moves', sa.Column('magic_estado', sa.Integer(), nullable=True))
    op.drop_column('moves', 'num_organs')
    op.drop_column('moves', 'num_protected')
    op.drop_column('moves', 'num_cure')
    op.drop_column('moves', 'num_virus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('num_virus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('moves', sa.Column('num_cure', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('moves', sa.Column('num_protected', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('moves', sa.Column('num_organs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('moves', 'magic_estado')
    op.drop_column('moves', 'brain_estado')
    op.drop_column('moves', 'heart_estado')
    op.drop_column('moves', 'intestine_estado')
    op.drop_column('moves', 'lungs_estado')
    # ### end Alembic commands ###
