"""Magic_Organ field

Revision ID: 55100cb1fa62
Revises: 27e15fcf7b62
Create Date: 2025-04-23 20:30:40.244153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55100cb1fa62'
down_revision: Union[str, None] = '27e15fcf7b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organs', sa.Column('magic_organ', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organs', 'magic_organ')
    # ### end Alembic commands ###
