"""Cambios en los usuarios2

Revision ID: a4d0b77a9926
Revises: 1064c34d4745
Create Date: 2025-04-10 16:43:03.976290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d0b77a9926'
down_revision: Union[str, None] = '1064c34d4745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'user_id')
    # ### end Alembic commands ###
