"""Añadido tipo de organo a carta2

Revision ID: ab7ed77b4596
Revises: c8f9caa3653c
Create Date: 2025-02-26 15:02:36.577157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7ed77b4596'
down_revision: Union[str, None] = 'c8f9caa3653c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
