"""Añadir nuevas tablas

Revision ID: ad4899b9a0ce
Revises: 
Create Date: 2025-02-26 13:31:44.164097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4899b9a0ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('player_bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_bodies_id'), 'player_bodies', ['id'], unique=False)
    op.create_table('player_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_cards_id'), 'player_cards', ['id'], unique=False)
    op.create_table('organs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('heart', 'stomach', 'brain', 'liver', name='organtype'), nullable=False),
    sa.Column('virus', sa.Boolean(), nullable=True),
    sa.Column('cure', sa.Integer(), nullable=True),
    sa.CheckConstraint('cure BETWEEN 0 AND 1', name='cure_value'),
    sa.ForeignKeyConstraint(['body_id'], ['player_bodies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organs_id'), 'organs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organs_id'), table_name='organs')
    op.drop_table('organs')
    op.drop_index(op.f('ix_player_cards_id'), table_name='player_cards')
    op.drop_table('player_cards')
    op.drop_index(op.f('ix_player_bodies_id'), table_name='player_bodies')
    op.drop_table('player_bodies')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
