"""Changing virus datatype

Revision ID: b2b9c9659867
Revises: 3e0545ffbaeb
Create Date: 2025-04-23 18:51:09.732068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b9c9659867'
down_revision: Union[str, None] = '3e0545ffbaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organs', 'virus',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='(case when virus is true then 1 else 0 end)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organs', 'virus',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               postgresql_using='(case when virus = 1 then true else false end)')
    # ### end Alembic commands ###
