"""Multiplayer game

Revision ID: bcf5b422fa5c
Revises: 1dc2fbeb1286
Create Date: 2025-05-02 14:44:39.415251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf5b422fa5c'
down_revision: Union[str, None] = '1dc2fbeb1286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('games', sa.Column('multiplayer', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('games', 'multiplayer', server_default=None)
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'multiplayer')
    # ### end Alembic commands ###
