"""Changing organ restrictions

Revision ID: d0baecb2527d
Revises: 1fe339e810ae
Create Date: 2025-04-23 19:42:28.162130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0baecb2527d'
down_revision: Union[str, None] = '1fe339e810ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cure_value', 'organs', type_='check')
    op.create_check_constraint('cure_value', 'organs', sa.text('cure BETWEEN 0 AND 3'))
    op.create_check_constraint('virus_value', 'organs', sa.text('virus BETWEEN 0 AND 2'))

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     # 1. Eliminar la nueva restricción de 'virus'
    op.drop_constraint('virus_value', 'organs', type_='check')
    
    # 2. Eliminar la nueva restricción de 'cure' (0-3)
    op.drop_constraint('cure_value', 'organs', type_='check')
    
    # 3. Restaurar la restricción original de 'cure' (0-2)
    op.create_check_constraint(
        'cure_value',
        'organs',
        sa.text('cure BETWEEN 0 AND 2')
    )
    pass
    # ### end Alembic commands ###
