"""Move modified

Revision ID: e8e811ed3179
Revises: bcf5b422fa5c
Create Date: 2025-05-14 18:45:12.969298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e811ed3179'
down_revision: Union[str, None] = 'bcf5b422fa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('num_virus', sa.Integer(), nullable=False))
    op.add_column('moves', sa.Column('num_cure', sa.Integer(), nullable=False))
    op.add_column('moves', sa.Column('num_protected', sa.Integer(), nullable=False))
    op.add_column('moves', sa.Column('num_organs', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'num_organs')
    op.drop_column('moves', 'num_protected')
    op.drop_column('moves', 'num_cure')
    op.drop_column('moves', 'num_virus')
    # ### end Alembic commands ###
