"""Cambios varios

Revision ID: e91b8c6ce9cf
Revises: d01eb979875d
Create Date: 2025-03-02 11:40:26.951080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91b8c6ce9cf'
down_revision: Union[str, None] = 'd01eb979875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('games_deck_id_key', 'games', type_='unique')
    op.drop_column('games', 'deck_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('games_deck_id_key', 'games', ['deck_id'])
    op.drop_table('deck_cards')
    # ### end Alembic commands ###
